### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by virajk31** [skeskinen/bert.cpp#8]
```
Traceback (most recent call last):
  File "/bert.cpp/examples/sample_client.py", line 69, in <module>
    embedding = embed_text(text)
  File "/bert.cpp/examples/sample_client.py", line 49, in embed_text
    embedding = embeddings_from_local_server(text, sock)
  File "/bert.cpp/examples/sample_client.py", line 16, in embeddings_from_local_server
    sock.sendall(s.encode())
BrokenPipeError: [Errno 32] Broken pipe
```

It works with small texts, but fails when passing a larger paragraph. Can someone give a help on this ?

**Comment by abhishekmamdapure** [comment]
Looking for solution
